[features]
seeds = false

[programs.localnet]
coffre_solana = "B1CUk72aS11qXKiJCpgN4fBqrrJfVaAbDN7PjACpUt4f"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/lat/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
